export const galleryItems = [
  {
    id: 1,
    type: "image",
    src: "/gallery/3 day webinar/IMG_4115.JPG",
    title: "Technical Webinar Session",
    event: "3-Day Technical Webinar",
    track: "Workshop",
    context: "Archived asset from 3-Day Technical Webinar.",
    year: "Cycle 2025 - 2026",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 2,
    type: "image",
    src: "/gallery/3 day webinar/IMG_4541.JPG",
    title: "Technical Webinar Session",
    event: "3-Day Technical Webinar",
    track: "Workshop",
    context: "Archived asset from 3-Day Technical Webinar.",
    year: "Cycle 2025 - 2026",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 3,
    type: "image",
    src: "/gallery/3 day webinar/IMG_4547.JPG",
    title: "Technical Webinar Session",
    event: "3-Day Technical Webinar",
    track: "Workshop",
    context: "Archived asset from 3-Day Technical Webinar.",
    year: "Cycle 2025 - 2026",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 4,
    type: "image",
    src: "/gallery/3 day webinar/IMG_4560.JPG",
    title: "Technical Webinar Session",
    event: "3-Day Technical Webinar",
    track: "Workshop",
    context: "Archived asset from 3-Day Technical Webinar.",
    year: "Cycle 2025 - 2026",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 5,
    type: "image",
    src: "/gallery/3 day webinar/IMG_4562.JPG",
    title: "Technical Webinar Session",
    event: "3-Day Technical Webinar",
    track: "Workshop",
    context: "Archived asset from 3-Day Technical Webinar.",
    year: "Cycle 2025 - 2026",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 6,
    type: "image",
    src: "/gallery/ACM -W launch/20250922_142834.jpg",
    title: "Diversity & Inclusion Panel",
    event: "ACM-W Structural Launch",
    track: "Diversity Panel",
    context: "Archived asset from ACM-W Structural Launch.",
    year: "Cycle 2024 - 2025",
    wing: "ACM-W Diversity Wing",
    assetType: "High-Res Photos",
  },
  {
    id: 7,
    type: "image",
    src: "/gallery/ACM -W launch/20250922_143728.jpg",
    title: "Diversity & Inclusion Panel",
    event: "ACM-W Structural Launch",
    track: "Diversity Panel",
    context: "Archived asset from ACM-W Structural Launch.",
    year: "Cycle 2024 - 2025",
    wing: "ACM-W Diversity Wing",
    assetType: "High-Res Photos",
  },
  {
    id: 8,
    type: "image",
    src: "/gallery/ACM -W launch/IMG20250922114048.jpg",
    title: "Diversity & Inclusion Panel",
    event: "ACM-W Structural Launch",
    track: "Diversity Panel",
    context: "Archived asset from ACM-W Structural Launch.",
    year: "Cycle 2024 - 2025",
    wing: "ACM-W Diversity Wing",
    assetType: "High-Res Photos",
  },
  {
    id: 9,
    type: "image",
    src: "/gallery/ACM -W launch/IMG20250922114630.jpg",
    title: "Diversity & Inclusion Panel",
    event: "ACM-W Structural Launch",
    track: "Diversity Panel",
    context: "Archived asset from ACM-W Structural Launch.",
    year: "Cycle 2024 - 2025",
    wing: "ACM-W Diversity Wing",
    assetType: "High-Res Photos",
  },
  {
    id: 10,
    type: "image",
    src: "/gallery/ACM -W launch/IMG20250922115220.jpg",
    title: "Diversity & Inclusion Panel",
    event: "ACM-W Structural Launch",
    track: "Diversity Panel",
    context: "Archived asset from ACM-W Structural Launch.",
    year: "Cycle 2024 - 2025",
    wing: "ACM-W Diversity Wing",
    assetType: "High-Res Photos",
  },
  {
    id: 11,
    type: "image",
    src: "/gallery/ACM -W launch/IMG20250922115547.jpg",
    title: "Diversity & Inclusion Panel",
    event: "ACM-W Structural Launch",
    track: "Diversity Panel",
    context: "Archived asset from ACM-W Structural Launch.",
    year: "Cycle 2024 - 2025",
    wing: "ACM-W Diversity Wing",
    assetType: "High-Res Photos",
  },
  {
    id: 12,
    type: "image",
    src: "/gallery/ACM -W launch/IMG20250922115711.jpg",
    title: "Diversity & Inclusion Panel",
    event: "ACM-W Structural Launch",
    track: "Diversity Panel",
    context: "Archived asset from ACM-W Structural Launch.",
    year: "Cycle 2024 - 2025",
    wing: "ACM-W Diversity Wing",
    assetType: "High-Res Photos",
  },
  {
    id: 13,
    type: "image",
    src: "/gallery/ACM -W launch/IMG_6399 3.JPG",
    title: "Diversity & Inclusion Panel",
    event: "ACM-W Structural Launch",
    track: "Diversity Panel",
    context: "Archived asset from ACM-W Structural Launch.",
    year: "Cycle 2024 - 2025",
    wing: "ACM-W Diversity Wing",
    assetType: "High-Res Photos",
  },
  {
    id: 14,
    type: "image",
    src: "/gallery/ACM SUMMIT/DSC_0623.JPG",
    title: "Summit Executive Snapshot",
    event: "ACM India Chapter Summit 2025",
    track: "Summit",
    context: "Archived asset from ACM India Chapter Summit 2025.",
    year: "Cycle 2024 - 2025",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 15,
    type: "image",
    src: "/gallery/ACM SUMMIT/DSC_0726.JPG",
    title: "Summit Executive Snapshot",
    event: "ACM India Chapter Summit 2025",
    track: "Summit",
    context: "Archived asset from ACM India Chapter Summit 2025.",
    year: "Cycle 2024 - 2025",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 16,
    type: "image",
    src: "/gallery/ACM SUMMIT/DSC_0970.JPG",
    title: "Summit Executive Snapshot",
    event: "ACM India Chapter Summit 2025",
    track: "Summit",
    context: "Archived asset from ACM India Chapter Summit 2025.",
    year: "Cycle 2024 - 2025",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 17,
    type: "image",
    src: "/gallery/ACM SUMMIT/DSC_1028.JPG",
    title: "Summit Executive Snapshot",
    event: "ACM India Chapter Summit 2025",
    track: "Summit",
    context: "Archived asset from ACM India Chapter Summit 2025.",
    year: "Cycle 2024 - 2025",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 18,
    type: "image",
    src: "/gallery/ACM SUMMIT/DSC_1085.JPG",
    title: "Summit Executive Snapshot",
    event: "ACM India Chapter Summit 2025",
    track: "Summit",
    context: "Archived asset from ACM India Chapter Summit 2025.",
    year: "Cycle 2024 - 2025",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 19,
    type: "image",
    src: "/gallery/ACM SUMMIT/DSC_1303.JPG",
    title: "Summit Executive Snapshot",
    event: "ACM India Chapter Summit 2025",
    track: "Summit",
    context: "Archived asset from ACM India Chapter Summit 2025.",
    year: "Cycle 2024 - 2025",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 20,
    type: "image",
    src: "/gallery/ACM SUMMIT/DSC_1341.JPG",
    title: "Summit Executive Snapshot",
    event: "ACM India Chapter Summit 2025",
    track: "Summit",
    context: "Archived asset from ACM India Chapter Summit 2025.",
    year: "Cycle 2024 - 2025",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 21,
    type: "image",
    src: "/gallery/ACM SUMMIT/DSC_1344.JPG",
    title: "Summit Executive Snapshot",
    event: "ACM India Chapter Summit 2025",
    track: "Summit",
    context: "Archived asset from ACM India Chapter Summit 2025.",
    year: "Cycle 2024 - 2025",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 22,
    type: "image",
    src: "/gallery/ACM SUMMIT/DSC_1372.JPG",
    title: "Summit Executive Snapshot",
    event: "ACM India Chapter Summit 2025",
    track: "Summit",
    context: "Archived asset from ACM India Chapter Summit 2025.",
    year: "Cycle 2024 - 2025",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 23,
    type: "image",
    src: "/gallery/ACM SUMMIT/DSC_1401.JPG",
    title: "Summit Executive Snapshot",
    event: "ACM India Chapter Summit 2025",
    track: "Summit",
    context: "Archived asset from ACM India Chapter Summit 2025.",
    year: "Cycle 2024 - 2025",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 24,
    type: "image",
    src: "/gallery/ACM SUMMIT/DSC_1504.JPG",
    title: "Summit Executive Snapshot",
    event: "ACM India Chapter Summit 2025",
    track: "Summit",
    context: "Archived asset from ACM India Chapter Summit 2025.",
    year: "Cycle 2024 - 2025",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 25,
    type: "image",
    src: "/gallery/ACM SUMMIT/DSC_1570.JPG",
    title: "Summit Executive Snapshot",
    event: "ACM India Chapter Summit 2025",
    track: "Summit",
    context: "Archived asset from ACM India Chapter Summit 2025.",
    year: "Cycle 2024 - 2025",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 26,
    type: "image",
    src: "/gallery/ACM SUMMIT/DSC_1657.JPG",
    title: "Summit Executive Snapshot",
    event: "ACM India Chapter Summit 2025",
    track: "Summit",
    context: "Archived asset from ACM India Chapter Summit 2025.",
    year: "Cycle 2024 - 2025",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 27,
    type: "image",
    src: "/gallery/ACM SUMMIT/DSC_1707.JPG",
    title: "Summit Executive Snapshot",
    event: "ACM India Chapter Summit 2025",
    track: "Summit",
    context: "Archived asset from ACM India Chapter Summit 2025.",
    year: "Cycle 2024 - 2025",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 28,
    type: "image",
    src: "/gallery/ACM SUMMIT/DSC_1752.JPG",
    title: "Summit Executive Snapshot",
    event: "ACM India Chapter Summit 2025",
    track: "Summit",
    context: "Archived asset from ACM India Chapter Summit 2025.",
    year: "Cycle 2024 - 2025",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 29,
    type: "image",
    src: "/gallery/ACM SUMMIT/DSC_1763.JPG",
    title: "Summit Executive Snapshot",
    event: "ACM India Chapter Summit 2025",
    track: "Summit",
    context: "Archived asset from ACM India Chapter Summit 2025.",
    year: "Cycle 2024 - 2025",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 30,
    type: "image",
    src: "/gallery/ACM SUMMIT/DSC_1785.JPG",
    title: "Summit Executive Snapshot",
    event: "ACM India Chapter Summit 2025",
    track: "Summit",
    context: "Archived asset from ACM India Chapter Summit 2025.",
    year: "Cycle 2024 - 2025",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 31,
    type: "image",
    src: "/gallery/ACM SUMMIT/DSC_1791.JPG",
    title: "Summit Executive Snapshot",
    event: "ACM India Chapter Summit 2025",
    track: "Summit",
    context: "Archived asset from ACM India Chapter Summit 2025.",
    year: "Cycle 2024 - 2025",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 32,
    type: "image",
    src: "/gallery/ACM SUMMIT/DSC_1796.JPG",
    title: "Summit Executive Snapshot",
    event: "ACM India Chapter Summit 2025",
    track: "Summit",
    context: "Archived asset from ACM India Chapter Summit 2025.",
    year: "Cycle 2024 - 2025",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 33,
    type: "video",
    src: "/gallery/bts.mp4",
    title: "Behind The Scenes Reel",
    event: "Chapter Event",
    track: "General",
    context: "Archived asset from Chapter Event.",
    year: "Cycle 2025 - 2026",
    wing: "ACM Main Council",
    assetType: "Cinematic Videos",
  },
  {
    id: 34,
    type: "video",
    src: "/gallery/intro reel.mp4",
    title: "Chapter Introduction Reel",
    event: "Chapter Event",
    track: "General",
    context: "Archived asset from Chapter Event.",
    year: "Cycle 2025 - 2026",
    wing: "ACM Main Council",
    assetType: "Cinematic Videos",
  },
  {
    id: 35,
    type: "video",
    src: "/gallery/WhatsApp Video 2026-06-09 at 6.09.47 PM.mp4",
    title: "Event Highlights 35",
    event: "Chapter Event",
    track: "General",
    context: "Archived asset from Chapter Event.",
    year: "Cycle 2025 - 2026",
    wing: "ACM Main Council",
    assetType: "Cinematic Videos",
  },
  {
    id: 36,
    type: "video",
    src: "/gallery/WhatsApp Video 2026-06-09 at 6.12.06 PM.mp4",
    title: "Event Highlights 36",
    event: "Chapter Event",
    track: "General",
    context: "Archived asset from Chapter Event.",
    year: "Cycle 2025 - 2026",
    wing: "ACM Main Council",
    assetType: "Cinematic Videos",
  },
  {
    id: 37,
    type: "video",
    src: "/gallery/WhatsApp Video 2026-06-09 at 6.12.23 PM.mp4",
    title: "Event Highlights 37",
    event: "Chapter Event",
    track: "General",
    context: "Archived asset from Chapter Event.",
    year: "Cycle 2025 - 2026",
    wing: "ACM Main Council",
    assetType: "Cinematic Videos",
  },
  {
    id: 38,
    type: "video",
    src: "/gallery/WhatsApp Video 2026-06-09 at 6.12.45 PM.mp4",
    title: "Event Highlights 38",
    event: "Chapter Event",
    track: "General",
    context: "Archived asset from Chapter Event.",
    year: "Cycle 2025 - 2026",
    wing: "ACM Main Council",
    assetType: "Cinematic Videos",
  },
  {
    id: 39,
    type: "image",
    src: "/gallery/work/DSC_4214.JPG",
    title: "Event Capture 39",
    event: "Chapter Event",
    track: "General",
    context: "Archived asset from Chapter Event.",
    year: "Cycle 2025 - 2026",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 40,
    type: "image",
    src: "/gallery/work/DSC_4434.JPG",
    title: "Event Capture 40",
    event: "Chapter Event",
    track: "General",
    context: "Archived asset from Chapter Event.",
    year: "Cycle 2025 - 2026",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 41,
    type: "image",
    src: "/gallery/work/DSC_5465.JPG",
    title: "Event Capture 41",
    event: "Chapter Event",
    track: "General",
    context: "Archived asset from Chapter Event.",
    year: "Cycle 2025 - 2026",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 42,
    type: "image",
    src: "/gallery/work/WhatsApp Image 2026-06-09 at 6.10.45 PM.jpeg",
    title: "Event Capture 42",
    event: "Chapter Event",
    track: "General",
    context: "Archived asset from Chapter Event.",
    year: "Cycle 2025 - 2026",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
  {
    id: 43,
    type: "image",
    src: "/gallery/work/WhatsApp Image 2026-06-09 at 6.16.00 PM.jpeg",
    title: "Event Capture 43",
    event: "Chapter Event",
    track: "General",
    context: "Archived asset from Chapter Event.",
    year: "Cycle 2025 - 2026",
    wing: "ACM Main Council",
    assetType: "High-Res Photos",
  },
];
